name: Test

on: [push]

jobs:
  test:
    # где запускаем
    runs-on: ubuntu-latest
      # что делаем
    steps:
        # выкаичваем репозиторий
        - uses: actions/checkout@v3
          # настраиваем java
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu' # дистрибутив java
            java-version: '17' # версия java
        - run: chmod +x ./gradlew
        - run: ./gradlew clean test -Dselenide.remote=http://loaclhost:4444/wd/hub

    -name: Generate Allure Report
      - if: always()
             run: |
               allure generate build/allure-result -o allure-report

        - uses: actions/checkout@v3
          if: always()
          continue-on-error: true
          with:
                ref: gh-pages
                path: gh-pages

        - uses: ./allure-report-action
          if: always()
          with:
            allure_results: build/allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history

        - uses: peaceiris/actions-gh-pages@v3
          if: always()
          env:
              PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              PUBLISH_BRANCH: gh-pages
              PUBLISH_DIR: allure-history